# Default config (override via CLI flags in train.py)
seed: 13
fs: 200
win_s: 4
overlap: 0.5
bands: [[0.5,4],[4,8],[8,13],[13,30]]
model:
  widths: [64,128,256]
  resblocks: 2
  cond_dims:
    artifact_k: 7
    intensity_dim: 1
optim:
  lr: 1.0e-4
  batch: 32
  steps: 120000
stft:
  win: 128
  hop: 64
  lambda: 0.1
sampling:
  ddim_steps: 50
  cfg_scale: 2.0
  cfg_pdrop: 0.2
